Archie/Models/Spot.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Archie.Models
{
    public class Spots
    {
        public int Id { get; set; }
        public DateTime dateInput { get; set; }

        public decimal goldVal { get; set; }
        public decimal silverVal { get; set; }
        public decimal platiniumVal { get; set; }
    }
}

Archie/Controllers/SpotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Archie.Data;
using Archie.Models;

namespace Archie.Controllers
{
    public class SpotsController : Controller
    {
        private readonly SyrakuzaContext _context;

        public SpotsController(SyrakuzaContext context)
        {
            _context = context;
        }

        // GET: Spots
        public async Task<IActionResult> Index()
        {
            List<Spots> results = new List<Spots>();

            using (var connection = System.Data.SqlClient.SqlClientFactory.Instance.CreateConnection())
            {
                connection.ConnectionString = ConnectionString;
                using (var command = connection.CreateCommand())
                {   
                    command.CommandText = "select id,dateInput,goldVal,silverVal,platiniumVal from archie.dbo.Spots;";
                    command.CommandType = System.Data.CommandType.Text;
                    connection.Open();

                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Spots sp = new Spots();
                            sp.Id = reader.GetInt32(reader.GetOrdinal("id"));
                            sp.dateInput = reader.GetDateTime(reader.GetOrdinal("dateInput"));
                            sp.goldVal = reader.GetDecimal(reader.GetOrdinal("goldVal"));
                            sp.silverVal = reader.GetDecimal(reader.GetOrdinal("silverVal"));
                            sp.platiniumVal = reader.GetDecimal(reader.GetOrdinal("platiniumVal"));
                            results.Add(sp);
                        
                        }
                    }
                }
            }
            return View(results);
        }
        public string ConnectionString
        {
            get
            {
                return new Db().ConnectionString;
            }
        }

        // GET: Spots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spot = await _context.Spots
                .SingleOrDefaultAsync(m => m.Id == id);
            if (spot == null)
            {
                return NotFound();
            }

            return View(spot);
        }

        // GET: Spots/Create
        public IActionResult Create()
        {
            return View();
        }
        /*public async Task<IActionResult> Diagram()
        {
            return View(await _context.Spots.ToListAsync());
        }*/
        public IActionResult newView()
        {
            return View();
        }
        public IActionResult Diagram()
        {
            return View();
        }
        public IActionResult XList()
        {
            //przekaznaie modelu danych do widoku, typ = lista
            var cenySpot = new[]
            {
              new Models.Spots()
              {
                dateInput = System.DateTime.Now,
                goldVal = 13,
                silverVal = 16,
                platiniumVal = 66
               },
             new Models.Spots()
              {
                dateInput = System.DateTime.Now,
                goldVal = 13,
                silverVal = 16,
                platiniumVal = 66
               }

            };
        
            return View(cenySpot);
        }


        // POST: Spots/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,dateInput,goldVal,silverVal,platiniumVal")] Spots spot)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(spot);
        }

        // GET: Spots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spot = await _context.Spots.SingleOrDefaultAsync(m => m.Id == id);
            if (spot == null)
            {
                return NotFound();
            }
            return View(spot);
        }

        // POST: Spots/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,dateInput,goldVal,silverVal,platiniumVal")] Spots spot)
        {
            if (id != spot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpotExists(spot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spot);
        }

        // GET: Spots/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spot = await _context.Spots
                .SingleOrDefaultAsync(m => m.Id == id);
            if (spot == null)
            {
                return NotFound();
            }

            return View(spot);
        }

        // POST: Spots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var spot = await _context.Spots.SingleOrDefaultAsync(m => m.Id == id);
            _context.Spots.Remove(spot);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpotExists(int id)
        {
            return _context.Spots.Any(e => e.Id == id);
        }
    }
}

Archie/Views/Spots/Create.cshtml
@model Archie.Models.Spots

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Spot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="dateInput" class="control-label"></label>
                <input asp-for="dateInput" class="form-control" />
                <span asp-validation-for="dateInput" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="goldVal" class="control-label"></label>
                <input asp-for="goldVal" class="form-control" />
                <span asp-validation-for="goldVal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="silverVal" class="control-label"></label>
                <input asp-for="silverVal" class="form-control" />
                <span asp-validation-for="silverVal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="platiniumVal" class="control-label"></label>
                <input asp-for="platiniumVal" class="form-control" />
                <span asp-validation-for="platiniumVal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Archie/Views/Spots/Delete.cshtml
@model Archie.Models.Spots

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Spot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dateInput)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateInput)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.goldVal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.goldVal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.silverVal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.silverVal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.platiniumVal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.platiniumVal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Archie/Views/Spots/Details.cshtml
@model Archie.Models.Spots

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Spot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dateInput)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateInput)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.goldVal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.goldVal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.silverVal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.silverVal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.platiniumVal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.platiniumVal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Archie/Views/Spots/Diagram.cshtml
@Model Archie.Models.Spots;

@{
    ViewData["Title"] = "Diagram";
}

<div id="container"></div>
<div class="invest-container">
    <h2>Invest time</h2>
    <label for="amount">Amount of deposit: </label><input style="margin-left:15px" type="number" id="amount" />
    <div>
        <label style="margin-right:18px;">Crypto of interest:</label>
        <select>
            <option value="BTC">BTC</option>
            <option value="ETH">ETH</option>
        </select>
    </div>

    <div class="slidecontainer">
        <input type="range" min="1" max="100" value="50" class="slider" id="range">
    </div>
    <label for="expected">Expected profit: </label><input style="margin-left:15px" type="text" id="expected" />
</div>

Archie/Views/Spots/Edit.cshtml
@model Archie.Models.Spots

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Spot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="dateInput" class="control-label"></label>
                <input asp-for="dateInput" class="form-control" />
                <span asp-validation-for="dateInput" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="goldVal" class="control-label"></label>
                <input asp-for="goldVal" class="form-control" />
                <span asp-validation-for="goldVal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="silverVal" class="control-label"></label>
                <input asp-for="silverVal" class="form-control" />
                <span asp-validation-for="silverVal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="platiniumVal" class="control-label"></label>
                <input asp-for="platiniumVal" class="form-control" />
                <span asp-validation-for="platiniumVal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Archie/Views/Spots/Index.cshtml
@model IEnumerable<Archie.Models.Spots>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<a href="@Url.Action("newView","Spots")">Actual Spot price</a>
<div>@Html.ActionLink("Actual Spot Price", "newView", "Spots")</div>
<div><a href="@Url.Action("XList","Spots")">Spot list</a></div>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dateInput)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.goldVal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.silverVal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.platiniumVal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.dateInput)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.goldVal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.silverVal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.platiniumVal)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Archie/Views/Spots/XCreate.cshtml
@{
    ViewData["Title"] = "XCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>XCreate</h2>

Archie/Views/Spots/XList.cshtml
@model IEnumerable<Archie.Models.Spots>

@{
    ViewData["Title"] = "XList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>XList</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dateInput)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.goldVal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.silverVal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.platiniumVal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.dateInput)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.goldVal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.silverVal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.platiniumVal)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Archie/Views/Spots/newView.cshtml
@{ 
    var cenySpot = new Archie.Models.Spots()
    {
        dateInput = System.DateTime.Now,
        goldVal = 13,
        silverVal = 16,
        platiniumVal = 66
    };
}
<div class="spoty">
    <h3>Example spot price</h3>
  
    <div class="details">
        <p>Cena zlota: @cenySpot.goldVal.ToString()</p>
        <p>Cena srebra: @cenySpot.silverVal.ToString()</p>
        <p>Cena platyny: @cenySpot.platiniumVal.ToString()</p>
        <p>Aktualne na dzien: @cenySpot.dateInput.ToString("g")</p>
    </div>

    @*
        Casting to String in case to meet a null val : (
        Multiple lines
    *@
    <p>
        Current Price:
        @if (cenySpot.goldVal == null)
        {
            @: [No]
        }
        else
        {
            <span>@cenySpot.goldVal.ToString("C")</span>
        }
    </p>
</div>